# A collection of functions that operate on stock list
# source("functions_stocklist.R")

loadStockListFromTxt <- function(filePath = "data/stocklist.txt"){
  # Load stock list from txt file that is generated by MS Excel in unicode format
  myStock = read.table(file = filePath,header=TRUE,fileEncoding = "UTF-8",colClasses = "character")
  return(myStock)
}

loadStockList <- function(filePath = "data/stocklist.RData"){
  load(file = filePath)
  return(data)
}

saveStockList <- function(dataList = c("data"), filePath = "data/stocklist.RData"){
  save(list = dataList, file = filePath)
}

getLoc <- function(symbol){
  if(substr(symbol,1,2)=="60"){
    loc = "SH"    # shanghai
  }
  if(substr(symbol,1,3)=="000" | substr(symbol,1,3)=="300" | substr(symbol,1,3)=="002"){
    loc = "SZ"    # shenzhen
  }
  return(loc)
}